export const SET_SALESCAKE='SET_SALESCAKE';
export const SET_ERROR_SALES='SET_ERROR_SALES';
export const SET_SALESCAKE_DELETE='SET_SALESCAKE_DELETE';
export const SET_SALESCAKE_PRICE='SET_SALESCAKE_PRICE';
export const SET_SALESCAKE_PRICE_ENABLE='SET_SALESCAKE_PRICE_ENABLE';
export const SET_SALESCAKE_ELEMENT_ERROR='SET_SALESCAKE_ELEMENT_ERROR';
export const SET_SALESPRICE_ELEMENT='SET_SALESPRICE_ELEMENT';
export const SET_SALESPRICE_INSERT_RESULT='SET_SALESPRICE_INSERT_RESULT';